services:

  hotel_db:
    image: mysql:8.0
    container_name: hotel_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hotel_dev_db
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3

  hotel_api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: hotel_api
    ports:
      - "8080:8080"
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      hotel_db:
        condition: service_healthy